# Generated by Django 3.1.2 on 2020-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='create date'),
        ),
    ]
