# Generated by Django 3.1.2 on 2020-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_auto_20201021_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmeasurement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='create_date',
            field=models.DateTimeField(verbose_name='create date'),
        ),
    ]
